---
title: "ASM-Project"
author: "Eloi Campeny Roig & Maria Paraskeva"
date: "2023-12-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Read Data
The chosen time series shows the apparent cement consumption in Spain (Construction Indicator) in thousands of tones.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
serie=window(ts(read.table("cemento.dat"),start=1990,freq=12))
print(round(serie,0))
```

```{r}
plot(serie,main="Apparent cement consumption in Spain (Thousand of tones)")
abline(v=1990:2020,col=4,lty=3)
```

```{r}
m=apply(matrix(serie,nr=12),2,mean)
v=apply(matrix(serie,nr=12),2,var)
plot(m,v,xlab="Medias anuales",ylab="Varianzas anuales",main="serie")
abline(lm(v~m),col=2,lty=3,lwd=2)
```

```{r}
boxplot(serie~floor(time(serie)))
```

```{r}
lnserie=log(serie)
plot(lnserie)
```

```{r}
m=apply(matrix(lnserie,nr=12),2,mean)
v=apply(matrix(lnserie,nr=12),2,var)
plot(m,v,xlab="Medias anuales",ylab="Varianzas anuales",main="serie")
abline(lm(v~m),col=2,lty=3,lwd=2)
```


```{r}
boxplot(lnserie~floor(time(lnserie)))
```

```{r}
plot(decompose(lnserie))
```

```{r}
monthplot(lnserie)
```

```{r}
ts.plot(matrix(lnserie,nrow=12),col=1:8)
```

```{r}
d12lnserie=diff(lnserie,12)
plot(d12lnserie)
abline(h=0)
```

```{r}
d1d12lnserie=diff(d12lnserie,1)
plot(d1d12lnserie)
abline(h=0)
abline(h=mean(d1d12lnserie),col=2,lwd=2)
```

```{r}
d1d1d12lnserie=diff(d1d12lnserie,1)
plot(d1d1d12lnserie)
abline(h=0)
abline(h=mean(d1d12lnserie),col=2,lwd=2)
```

```{r}
var(lnserie)
var(d1d12lnserie)
var(d1d1d12lnserie)

```

```{r}
par(mfrow=c(1,2))
acf(d1d12lnserie,ylim=c(-1,1),col=c(2,rep(1,11)),lwd=2,lag.max=72)
pacf(d1d12lnserie,ylim=c(-1,1),col=c(rep(1,11),2),lwd=2,lag.max=72)
```

AR(2), AR(4)